educa/educa/urls.py
from django import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include,path
from courses.views import CourseListView,CustomLoginView



urlpatterns = [
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls, name='admin_site'),
    path('course/',include('courses.urls')),
    path('',CourseListView.as_view(), name='course_list'),
    path('students/',include('students.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
    mimetypes.add_type("text/css", ".css", True)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT)

educa/students/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('register/',
         views.StudentRegistrationView.as_view(),
         name='student_registration'),
    path('enroll-course/',
         views.StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(),
         name='student_course_list'),
    path('course/<pk>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail'),
    path('course/<int:pk>/<int:module_id>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
    path('profile/',
         views.StudentProfile.as_view(),
         name='student_profile'),
    path('update-profile/',
         views.StudentProfileUpdateView.as_view(),
         name='update_profile'),
    path('update-profile-image/',
         views.ProfileImageUpdateView.as_view(),
         name='update_profile_image'),
    path('course/<int:course_id>/exams/',
         views.StudentExamListView.as_view(),
         name='student_exam_list'),
    path('course/<int:course_id>/exams/<int:exam_id>/',
         views.StudentExamDetailView.as_view(),
         name='student_exam_detail'),
    path('course/<int:course_id>/exams/<int:exam_id>/exam/',
         views.StudentTakeExamView.as_view(),
         name='student_take_exam'),
    path('course/<int:course_id>/exam/<int:exam_id>/results/<int:exam_attempt_id>/',
         views.StudentExamResultsView.as_view(),
         name='student_exam_result'),
    path('student_analytics',
         views.StudentAnalyticsDashboard.as_view(),
         name='student_analytics'),
    path('enrollment/',
         views.StudentEnrollmentView.as_view(),
         name='student_enrollment'),
    path('payment/',
         views.CoursePaymentView.as_view(),
         name='course_payment'),
    path('payment/success/',
         views.PaymentSuccessView.as_view(),
         name='payment_success'),
    path('payment/cancel/',
         views.PaymentCancelView.as_view(),
         name='payment_cancel'),
    path('webhook/stripe/',
         views.stripe_webhook,
         name='stripe_webhook'),
    path('payment/receipt/<int:pk>/',
         views.PaymentReceiptView.as_view(),
         name='payment_receipt'),
    path('admin/payment/receipt/<int:transaction_id>/',
         views.AdminPaymentReceiptView.as_view(),
         name='admin_payment_receipt'),
    path('receipts/',
         views.StudentReceiptsView.as_view(),
         name='student_receipts'),
    path('certificate/<int:course_id>/<int:completion_id>/',
         views.StudentCertificateView.as_view(),
         name='student_certificate'),
    path('certificates/',
         views.StudentCertificatesListView.as_view(),
         name='student_certificates'),
    path('admin/certificate/<int:course_id>/<int:completion_id>/',
         views.AdminCertificateView.as_view(),
         name='admin_certificate'),
]

educa/courses/models.py
import uuid
from itertools import count
from os.path import abspath

from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models import F, FloatField, Avg, Case, When
from django.db.models.fields import return_None
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify

from educa.utils import build_absolute_uri
from .fields import OrderField
from django.template.loader import render_to_string



# Create your models here.
#We are gonna have Subject, Course, Content
#For Example Subject = Mathematics, Courses = Math 1, Math 2 and Content = Text/Image/Video

class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    duration = models.TextField(blank=True)
    order = models.PositiveIntegerField(default=0,)
    class Meta:
        ordering = ['order']
    def __str__(self):
        return self.title


class Course(models.Model):
    #Who created the course
    owners = models.ManyToManyField(User,
                                    related_name='courses_created',
                                    blank=True)
    subject = models.ForeignKey(Subject,
                                related_name='courses',
                                on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True,
                            auto_created=True)
    overview = models.TextField()
    duration = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True) #set when new object is created
    price = models.DecimalField(max_digits=10,decimal_places=2, default=0)
    order = models.PositiveIntegerField(default=0,)

    class Meta:
        ordering = ['order'] # - means descending order
    def __str__(self):
        return self.title
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args,**kwargs)

class Module(models.Model):
    course = models.ForeignKey(Course,
                               related_name='modules',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])
    def __str__(self):
        #return self.title
        return f'{self.order}.{self.title}'
    class Meta:
        ordering = ['order']

class Content(models.Model):
    module = models.ForeignKey(Module,
                               related_name='contents',
                               on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType,
                                     on_delete= models.CASCADE,
                                     limit_choices_to={'model__in':('text','video','image','file','exercise')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])
    class Meta:
        ordering = ['order']

class ItemBase(models.Model):
    owner = models.ForeignKey(User,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
    def __str__(self):
        return self.title

    def render(self):
        return render_to_string(
            f'courses/content/{self._meta.model_name}.html',
            {'item': self}
        )

class Text(ItemBase):
    content = models.TextField()

class File(ItemBase):
    file = models.FileField(upload_to='files')

class Image(ItemBase):
    file = models.FileField(upload_to='images')

class Video(ItemBase):
    url = models.URLField()

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='images/profile_pics/default.jpg',upload_to='images/profile_pics',null=True,blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'


QuestionTypes = (
    ('MCQ','Multiple Choice'),
    ('TF','True or False'),
    ('ESSAY','Essay'),)


class Question(models.Model):
    text = models.TextField()
    exercise = models.ForeignKey('Exercise',blank=True,on_delete=models.CASCADE,null=True)
    exam = models.ManyToManyField('Exam',blank=True, related_name='questions')
    question_type = models.CharField(max_length=200,choices=QuestionTypes, default='ESSAY')
    is_true = models.BooleanField(default=False,null=True,blank=True)
    score = models.DecimalField(max_digits=5,decimal_places=2,default=0)


    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question,blank=True,on_delete=models.CASCADE,null=True, related_name='answers')
    text = models.TextField(blank=True,null=True)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

class Exercise(models.Model):
    title = models.CharField(max_length=200)
    question_description = models.TextField(blank=True,null=True)
    answer = models.TextField(blank=True,null=True)
    duration = models.DurationField(blank=True,null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,blank=True,null=True)
    module = models.ForeignKey(Module,on_delete=models.CASCADE,blank=True,null=True,related_name='exercises')
    question_file = models.FileField(upload_to='files/exercise_files/question_files',blank=True,null=True)
    answer_file = models.FileField(upload_to='files/exercise_files/answer_files',blank=True,null=True)
    visible = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    @property
    def duration_hm(self):
        total_minutes = int(self.duration.total_seconds() // 60)
        hours, minutes = divmod(total_minutes, 60)
        return f'{hours:02d}:{minutes:02d}'





class AcademicYear(models.Model):
    name = models.CharField(max_length=9, help_text="Academic year in format YYYY-YYYY (e.g. 2024-2025)")
    start_date = models.DateField()
    end_date = models.DateField()
    is_current = models.BooleanField(default=False)

    class Meta:
        ordering = ['-start_date']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.is_current:
            AcademicYear.objects.filter(is_current=True).exclude(id=self.id).update(is_current=False)
        super().save(*args, **kwargs)


class Exam(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True,null=True)
    duration = models.DurationField(blank=True,null=True)
    start_time = models.DateTimeField(blank=True,null=True)
    end_time = models.DateTimeField(blank=True,null=True)
    passing_score = models.DecimalField(max_digits=5,decimal_places=2,blank=True,null=True)
    total_score = models.DecimalField(max_digits=5,decimal_places=2,blank=True,null=True)
    attempts_allowed = models.PositiveIntegerField(blank=True,null=True)
    is_active = models.BooleanField(default=False)
    is_graded = models.BooleanField(default=False)
    is_final = models.BooleanField(default=False, help_text="Mark this exam as the final exam for the course.")
    guid = models.UUIDField(unique=True,default=uuid.uuid4,editable=False)
    course = models.ForeignKey(Course,
                                related_name='exams',
                                on_delete=models.CASCADE)
    academic_year = models.ForeignKey(AcademicYear,on_delete=models.CASCADE,related_name='exams')


    def __str__(self):
        return self.title

    def all_attempts_graded(self):
        finalized_attempts = StudentExamAttempt.objects.filter(exam = self, is_finalized=True)

        if not finalized_attempts.exists():
            return False

        return all(attempt.is_graded for attempt in finalized_attempts)

class StudentCourseEnrollment(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student_enrollment')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_enrollment')
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE, related_name='academic_year_enrollment')
    enrollment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('student', 'course', 'academic_year')

    def __str__(self):
        return f'{self.student.username} enrolled {self.course.title} in {self.academic_year.name} on {self.enrollment_date.strftime("%Y-%m-%d")}.'


class StudentCourseCompletion(models.Model):
    enrollment = models.OneToOneField(StudentCourseEnrollment, on_delete=models.CASCADE, related_name='completion')
    completed_date = models.DateTimeField(auto_now_add=True)
    certificate_issued = models.BooleanField(default=False)

    def __str__(self):
       return f'{self.enrollment.student.username} completed {self.enrollment.course.title} in {self.enrollment.academic_year.name} on {self.completed_date.strftime("%Y-%m-%d")}.'





class StudentExamAttempt(models.Model):
    # student = models.ForeignKey(User,on_delete=models.CASCADE)
    enrollment = models.ForeignKey(StudentCourseEnrollment,on_delete=models.CASCADE,related_name='exam_attempts')
    exam = models.ForeignKey(Exam,on_delete=models.CASCADE)
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(blank=True,null=True)

educa/students/models.py
from django.db import models

# Create your models here.

educa/students/forms.py
from django import forms
from courses.models import *
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User



class CourseEnrollForm(forms.Form):
    courses = forms.ModelMultipleChoiceField(
        queryset=Course.objects.none(),
        label='Courses',
        widget=forms.CheckboxSelectMultiple
    )
    academic_year = forms.ModelChoiceField(
        queryset= AcademicYear.objects.all(),
        widget=forms.HiddenInput
    )

    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user',None)
        super(CourseEnrollForm,self).__init__(*args,**kwargs)
        current_year = AcademicYear.objects.filter(is_current=True).first()
        if current_year:
            self.fields['academic_year'].initial = current_year

        self.all_courses = Course.objects.all().order_by('subject__title','title')

        self.unavailable_courses = []
        if user and user.is_authenticated:
            self.unavailable_courses = StudentCourseEnrollment.objects.filter(student=user,
                                                                              ).values_list('course_id',flat=True)
            self.fields['courses'].queryset = Course.objects.exclude(id__in=self.unavailable_courses)
        else:
            self.fields['courses'].queryset = Course.objects.none()

class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('username','first_name','last_name','email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class StudentProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')

    def unique_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError('Email already exists.')
        return email

class ProfileImageUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

educa/students/templates/students/course/detail.html
{% extends "base.html" %}
{% block title %}
    {{ object.title }}
{% endblock %}
{% block content %}
    <h1>
        {{ module.title }}
    </h1>
    <div class="contents">
        <h3>Modules</h3>
        <ul id="modules">
            {% for m in object.modules.all %}
                <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
                    <a href="{% url 'student_course_detail_module' object.id m.id %}">
                    <span>
                        Module <span class="order">{{ m.order|add:1 }}</span>
                    </span>
                        <br>
                        {{ m.title }}
                    </a>
                </li>
            {% empty %}
                <li>No modules yet.</li>
            {% endfor %}
        </ul>
        <p><a href="{% url 'student_course_list' %}">Return to my courses</a></p>
    </div>
    <div class="module" style="overflow: auto;" id="course_detail">
        {% if module.contents.exists %}
            {% for content in module.contents.all %}
                {% with item=content.item %}
                    <h2>{{ item.title }}</h2>
                    {{ item.render }}
                {% endwith %}
            {% endfor %}
        {% else %}
            <h2>Contents</h2>
            <p>No contents yet.</p>
        {% endif %}
        <div id="exercises">
            <h2>Exercises</h2>
            {% if available_exercises %}
                <ul>
                    {% for exercise in available_exercises %}
                        <li>
                            <a href="{% url 'exercise_detail' course.id module.id exercise.id %}">{{ exercise.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No exercises yet.</p>
            {% endif %}
        </div>

    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.querySelectorAll('#course_detail a:not(#exercises a)').forEach(function (el) {
                el.classList.add('btn', 'btn-primary', 'btn-sm');
            });
        });

    </script>
{% endblock %}

educa/students/templates/students/course/enroll.html
{% extends 'base.html' %}
{% block title %}
    Enroll in Courses
{% endblock %}
{% block content %}
    <h1>Enroll in Courses</h1>

    <div class="module">
        <h2>Available Courses for {{ current_academic_year }}</h2>

        {% if form.courses.field.queryset.exists  or subjects_with_courses %}
            <div class="enrollment-container">
                <div class="enrollment-info">
                    <p class="academic-year-info">
                        <i class="fa fa-calendar-alt"></i>
                        Academic Year:  <strong> {{ current_academic_year }}</strong>
                    </p>
                    <p class="enrollment-instructions">
                        <i class="fa fa-info-circle"></i>
                        Please select the courses you want to enroll in for the current academic year.<br>
                        You can select multiple courses by checking the boxes next to each course name.<br>
                        Courses that you are already enrolled in are grayed out and cannot be selected.
                    </p>
                </div>

                <form method="post" class="enrollment-form">
                    {% csrf_token %}
                    {{ form.academic_year }}

                    <div class="course-selection">
                        {% for subject, courses in subjects_with_courses.items %}
                            <div class="subject-group">
                                <h3><i class="fas fa-book"></i> {{ subject.title }}</h3>

                                <div class="course-checkboxes">
                                    {% for course_info in courses %}
                                        <div class="course-checkbox {% if course_info.unavailable %}unavailable{% endif %}">
                                            {% if course_info.unavailable %}
                                                <input type="checkbox" disabled id="id_courses_{{ course_info.course.id }}" name="courses" value="{{ course_info.course.id }}" class="disabled-course">
                                                <label for="id_courses_{{ course_info.course.id }}" class="disabled-course">{{ course_info.course.title }} <span class="course-price">{{ course_info.course.price }}€</span>
                                                </label>
                                            {% else %}
                                                <input type="checkbox" id="id_courses_{{ course_info.course.id }}" name="courses" value="{{ course_info.course.id }}">
                                                <label for="id_courses_{{ course_info.course.id }}">{{ course_info.course.title }} <span class="course-price">{{ course_info.course.price }}€</span></label>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-shopping-cart"></i> Proceed to payment
                        </button>
                    </div>
                </form>
            </div>
        {% else %}
            <div class="enrollment-message">
                <i class="fas fa-info-circle"></i>
                <p>You are already enrolled in all available courses for this academic year.</p>
                <a href="{% url 'student_course_list' %}" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i>Back to courses
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}

educa/students/templates/students/course/list.html
{% extends "base.html" %}
{% block title %}My Courses{% endblock %}
{% block content %}
    <h1>My courses</h1>
    <div class="student-courses-container">
        {% if enrollments %}
            {% regroup enrollments by course.subject as subject_list %}

            {% for subject in subject_list %}
                <div class="subject-section">
                    <h2 class="subject-title">{{ subject.grouper.title }}</h2>

                    <div class="course-grid">
                        {% for enrollment in subject.list %}
                            <div class="course-card {% if enrollment.academic_year.is_current %}current-course{% endif %}">
                                <div class="course-header">
                                    <h3>{{ enrollment.course.title }}</h3>
                                    <div class="course-meta">
                                        <div class="academic-year">
                                            <i class="fas fa-calendar-alt"></i> {{ enrollment.academic_year.name }}
                                        </div>
                                        <div class="subject-badge">
                                            <i class="fas fa-book"></i> {{ enrollment.course.subject.title }}
                                        </div>
                                        <div class="completion-badge">
                                            {% if enrollment.completion_status %}
                                                <span class="badge badge-success">
                                                    <i class="fas fa-check-circle"></i> Completed
                                                </span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="course-actions">
                                        <a href="{% url 'student_course_detail' enrollment.course.id %}" class="btn {% if enrollment.academic_year.is_current %}btn-primary{% else %}btn-secondary{% endif %}">
                                            <i class="fas fa-book-open"></i> View Course
                                        </a>
                                        <a href="{% url 'student_exam_list' enrollment.course.id %}" class="btn btn-secondary">
                                            <i class="fas fa-file-alt"></i> Access Exams
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="empty-state">
                <p>You are not enrolled in any courses yet.</p>
                <a href="{% url 'course_list' %}" class="action-button primary">Browse courses</a>
            </div>
        {% endif %}
    </div>
{% endblock %}